@url = http://localhost:3000
### Obtener todos los clientes
GET {{url}}/clientes
Accept: application/json

### Obtener cliente por ID
GET {{url}}/clientes/1
Accept: application/json

### Crear nuevo cliente
POST {{url}}/clientes
Content-Type: application/json

{
  "nombre": "Facundo",
  "apellido": "Gutierrez",
  "telefono": "+1234567876",
  "email": "juannnnn@gmail.com"
}

### Actualizar cliente
PUT {{url}}/clientes/5
Content-Type: application/json

{
  "nombre": "Juan",
  "apellido": "Perez",
  "telefono": "+1234567872",
  "email": "juannito@gmail.com"
}

### Eliminar cliente
DELETE {{url}}/clientes/1