@url = http://localhost:3000
### Obtener todos los clientes
GET {{url}}/clientes
Accept: application/json

### Obtener cliente por ID
GET {{url}}/clientes/1
Accept: application/json

### Crear nuevo cliente
POST {{url}}/clientes
Content-Type: application/json

{
  "nombre": "Pedro",
  "apellido": "Gutierrez",
  "telefono": "+1234567871",
  "email": "juan@gmail.com"
}

### Actualizar cliente
PUT {{url}}/clientes/4
Content-Type: application/json

{
  "nombre": "Juan",
  "apellido": "Perez",
  "telefono": "+1234567888",
  "email": "juannn@gmail.com"
}

### Eliminar cliente
DELETE {{url}}/clientes/1