@url = http://localhost:3000

### Obtener todos los horarios
GET {{url}}/horarios
Accept: application/json

### Ver disponibilidad por fecha
GET {{url}}/horarios/disponibilidad?fecha=2025-10-15
Accept: application/json

### Ver disponibilidad por fecha mes
GET {{url}}/horarios/disponibilidad/rango?fecha_inicio=2025-10-01&fecha_fin=2025-10-31
Accept: application/json

### Crear nuevo horario
POST {{url}}/horarios
Content-Type: application/json

{
  "dia_semana":"sabado", 
  "hora_inicio": "18:00:00",
  "hora_fin": "22:00:00",
  "activo": true
}

### Actualizar horario
PUT {{url}}/horarios/9
Content-Type: application/json

{
  "dia_semana": "martes",
  "hora_inicio": "18:00:00",
  "hora_fin": "22:00:00",
  "activo": true
}