@url = http://localhost:3000

### Obtener todos los productos
GET {{url}}/productos
Accept: application/json

### Obtener producto por ID
GET {{url}}/productos/1
Accept: application/json

### Filtrar productos por categoría
GET {{url}}/productos?categoria_id=2
Accept: application/json

### Crear nuevo producto
POST {{url}}/productos
Content-Type: application/json

{
  "nombre": "Cerveza Budweiser",
  "descripcion": "Cerveza IPA local",
  "precio": 8.50,
  "categoria_id": 2
}

### Actualizar producto
PUT {{url}}/productos/4
Content-Type: application/json

{
  "nombre": "Cerveza Budweiser ",
  "precio": 9.50,
  "descripcion": "Cerveza de 475ml",
  "categoria_id": 3
}

### Eliminar producto
DELETE {{url}}/productos/3