@url = http://localhost:3000

### Obtener todas las reservas
GET {{url}}/reservas
Accept: application/json

### Obtener reservas filtradas por fecha
GET {{url}}/reservas?fecha=2025-10-16
Accept: application/json

### Obtener reserva por ID
GET {{url}}/reservas/2
Accept: application/json

### Crear nueva reserva
POST {{url}}/reservas
Content-Type: application/json

{
  "cliente_id": 6,
  "fecha_reserva": "2025-10-15",
  "hora_inicio": "18:00:00",
  "hora_fin": "20:00:00",
  "numero_personas": 15
  
}


### Actualizar reserva
PUT {{url}}/reservas/1
Content-Type: application.json

{
  "cliente_id": 1,
  "horario_id": 1,
  "numero_personas": 5,
  "notas": "Aumentar número de personas",
  "estado": "confirmada"
}

### Cancelar reserva
DELETE {{url}}/reservas/1